[package]
name = "plasma-core"
version = "0.1.0"
authors = ["Cryptoeconomics Lab <info@cryptoeconomicslab.com>"]
edition = "2018"

[dependencies]
bytes = "0.4.12"
ethereum-types = "0.4"
rlp = "0.3.0"
